name: 'Hello World'
description: 'Greet someone and record the time'
inputs: # input parameter are stored as environment variables
  who-to-greet: # id of input
    description: 'who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
